name = "CAN"
uuid = "bffc1db9-6142-4b2c-b5cf-b017e7edc3de"
authors = ["Soichiro Fukamachi <ichiro.kazusa@gmail.com>"]
version = "0.0.1"

[deps]
CANalyze = "2dc4fe6c-d2be-46ad-ace5-0bbcd4825534"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
CANalyze = "1.6.0"
StaticArrays = "1.9.15"
julia = "1.11"